name: balta_dbt
version: 1.0.0
profile: balta_duckdb
model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target"]
config-version: 2
vars:
  as_of_date: "{{ run_started_at.strftime('%Y-%m-%d') }}"
