name: "balta"
version: "1.0"
config-version: 2
profile: "balta"

model-paths: ["models"]
seed-paths: ["seeds/bronze"]
macro-paths: ["macros"]

models:
  balta:
    +materialized: table
    silver:
      +materialized: table
    gold:
      +materialized: table

seeds:
  balta:
    +quote_columns: false